version: '3.7'

services:
  web:
    build: .
    volumes:
      &web-volumes
      - &app-volume .:/task_manager:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
    ports:
      - 3330:3330
      - 3331:3331
      - 3332:3332
    depends_on:
      - db
    environment:
      &web-environment
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 3330
      RUBYOPT: -W:no-deprecated -W:no-experimental
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

      ROLLBAR_ACCESS_TOKEN: fake
      NEWRELIC_LICENSE_KEY: fake
    command: bundle exec rails s -b '0.0.0.0' -p 3330

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  bundle_cache:
